import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {createPublicClient,http,encodeFunctionData,parseAbi} from 'viem';
import './style.css';
import {api} from './api.js';
import {watchWallets,walletError} from './wallet.js';

const CHAIN='0xb626';
const faucet='https://faucet.testnet.chain.robinhood.com/';
const explorer='https://explorer.testnet.chain.robinhood.com';
const regions=['Africa','Europe','Asia','Americas','Oceania'];
const short=a=>a?`${a.slice(0,6)}…${a.slice(-4)}`:'';
const abi=parseAbi(['function recordScore(bytes32 roundId,uint256 day,uint256 points,uint256 deadline,bytes signature)','function recordedRound(bytes32) view returns (bool)','function scorer() view returns (address)']);
function Globe(){return <div className="globe-scene" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="globe"><svg viewBox="0 0 400 400"><defs><clipPath id="earth"><circle cx="200" cy="200" r="185"/></clipPath><radialGradient id="ocean"><stop stopColor="#284e43"/><stop offset="1" stopColor="#102c28"/></radialGradient></defs><circle cx="200" cy="200" r="185" fill="url(#ocean)"/><g clipPath="url(#earth)" stroke="#73ab87" strokeWidth=".6" fill="none" opacity=".32">{[55,105,155,200,245,295,345].map(y=><ellipse key={y} cx="200" cy={y} rx="190" ry="24"/>)}{[45,100,155].map(rx=><ellipse key={rx} cx="200" cy="200" rx={rx} ry="185"/>)}<path d="M15 200h370M200 15v370"/></g><g fill="#b7c57b" opacity=".84" stroke="#d8e6a0" strokeWidth="1"><path d="M116 102l22-17 34 7 11 17-14 15-25 6-8 23-20-5-19-25zM145 161l35-16 38 18 12 39-23 25-5 42-24 24-16-25-7-49-24-28zM196 92l22-16 36 6 18 15 46 7 35 27-15 33-38-1-14 24-22-16-17-32-23 5-20-24-25 9-7-18zM290 270l31-17 37 18-5 31-37 11-31-19zM69 91l25 10-7 34-20 20-26-20z"/></g><g fill="#effaad"><circle cx="173" cy="189" r="5"/><circle cx="217" cy="105" r="5"/><circle cx="306" cy="148" r="5"/></g><path d="M173 189Q159 120 217 105T306 148" fill="none" stroke="#f4d37c" strokeWidth="2" strokeDasharray="4 7"/></svg></div><span className="globe-tag tag-one">↗ NEXT STOP: DISCOVERY</span><span className="globe-tag tag-two">05 REGIONS · ONE PASSPORT</span></div>}
function App(){
 const [wallets,setWallets]=useState([]),[walletPicker,setWalletPicker]=useState(false),[activeProvider,setActiveProvider]=useState(null);
 const walletDialog=useRef(null),walletTrigger=useRef(null);
 const [view,setView]=useState('home'),[config,setConfig]=useState(null),[player,setPlayer]=useState(null),[round,setRound]=useState(null),[practice,setPractice]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[menu,setMenu]=useState(false),[board,setBoard]=useState(null),[period,setPeriod]=useState('week'),[clock,setClock]=useState(Date.now()),[tx,setTx]=useState(null);
 const provider=useRef(null),lock=useRef(false),offset=useRef(0);
 const refreshPlayer=async()=>{const r=await api('me');setPlayer(r.player);};
 useEffect(()=>{api('config').then(c=>{setConfig(c);if(c.rankedReady)refreshPlayer().catch(()=>{});}).catch(()=>setError('Unable to reach the game service. Please refresh.'));const timer=setInterval(()=>setClock(Date.now()),250);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(view==='leaderboard'){let live=true;setBoard(null);api(`leaderboard?period=${period}`).then(r=>{if(live)setBoard(r.players);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};}},[view,period]);
 useEffect(()=>watchWallets(window,setWallets),[]);
 useEffect(()=>{if(walletPicker)walletDialog.current?.showModal();else if(walletDialog.current?.open){walletDialog.current.close();walletTrigger.current?.focus();}},[walletPicker]);
 useEffect(()=>{const p=activeProvider;if(!p?.on)return;const changed=accounts=>{if(accounts?.[0]?.toLowerCase()===player?.address)return;provider.current=null;setActiveProvider(null);setPlayer(null);setRound(null);setView('home');api('auth/logout',{}).catch(()=>{});setNotice('Wallet changed. Sign in again to continue ranked play.');};p.on('accountsChanged',changed);return()=>p.removeListener?.('accountsChanged',changed);},[activeProvider,player?.address]);
 const run=async fn=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setNotice('');setError(walletError(e));}finally{lock.current=false;setBusy(false);}};
 const navigate=v=>{setView(v);setError('');setNotice('');setMenu(false);};
 function connect(){walletTrigger.current=document.activeElement;setError('');setWalletPicker(true);}
 async function signIn(p){setWalletPicker(false);await run(async()=>{
   if(!p)throw new Error('Select your installed wallet first.');
   setNotice('Unlock your wallet and approve the connection request.');
   const accounts=await p.request({method:'eth_requestAccounts'});const address=accounts[0];if(!address)throw new Error('No wallet account selected.');
   const chainId=Number(await p.request({method:'eth_chainId'}));
   const c=await api('auth/challenge',{address,chainId});
   setNotice('Confirm the free ATLAS sign-in message in your wallet. No transaction or token approval is requested.');
   const hex=`0x${Array.from(new TextEncoder().encode(c.message),b=>b.toString(16).padStart(2,'0')).join('')}`;
   const signature=await p.request({method:'personal_sign',params:[hex,address]});
   const latest=await p.request({method:'eth_accounts'});if(latest[0]?.toLowerCase()!==address.toLowerCase())throw new Error('Account changed while signing. Please reconnect.');
   await api('auth/verify',{nonce:c.nonce,signature});provider.current=p;setActiveProvider(p);await refreshPlayer();setNotice('Passport connected. You are ready for today\'s expedition.');
 });}
 const acceptRound=r=>{offset.current=r.serverNow-Date.now();setRound(r);};
 async function startRanked(){if(!player){await connect();return;}await run(async()=>{acceptRound(await api('round/start',{}));setPractice(null);setTx(null);setView('play');});}
 async function startPractice(){await run(async()=>{const {questions}=await api('practice');setPractice({questions,index:0,score:0,correct:0,streak:0,deadline:Date.now()+25000,feedback:null,done:false});setRound(null);setTx(null);setView('play');});}
 const current=practice?{...practice,question:practice.done||practice.feedback?null:{...practice.questions[practice.index],number:practice.index+1,deadline:practice.deadline},awaitingNext:!!practice.feedback&&!practice.done,size:5}:round;
 const remaining=current?.question?Math.max(0,Math.ceil((current.question.deadline-(clock+(practice?0:offset.current)))/1000)):0;
 async function answer(choice){await run(async()=>{
   if(practice){setPractice(p=>{if(p.feedback||p.done)return p;const q=p.questions[p.index];const timedOut=Date.now()>p.deadline;const correct=!timedOut&&choice===q.answer;const streak=correct?p.streak+1:0;const points=correct?100+streak*10:0;return {...p,score:p.score+points,correct:p.correct+Number(correct),streak,feedback:{correct,timedOut,points,answer:q.options[q.answer],explanation:q.explanation},done:p.index===4};});}
   else{const r=await api('round/answer',{roundId:round.id,number:round.question.number,choice});acceptRound(r);if(r.done)await refreshPlayer();}
 });}
 async function next(){await run(async()=>{if(practice)setPractice(p=>({...p,index:p.index+1,feedback:null,deadline:Date.now()+25000}));else acceptRound(await api('round/next',{roundId:round.id}));});}
 async function record(){await run(async()=>{
   const p=provider.current||window.ethereum;if(!p)throw new Error('Open your connected EVM wallet to record this score.');
   const accounts=await p.request({method:'eth_requestAccounts'});if(accounts[0]?.toLowerCase()!==player.address.toLowerCase())throw new Error('Select the wallet used for this expedition.');
   try{await p.request({method:'wallet_switchEthereumChain',params:[{chainId:CHAIN}]});}catch(e){if(e.code!==4902)throw e;await p.request({method:'wallet_addEthereumChain',params:[{chainId:CHAIN,chainName:'Robinhood Chain Testnet',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:['https://rpc.testnet.chain.robinhood.com'],blockExplorerUrls:[explorer]}]});}
   if(await p.request({method:'eth_chainId'})!==CHAIN)throw new Error('Switch to Robinhood Chain Testnet first.');
   const receipt=await api('round/receipt',{roundId:round.id});
   const client=createPublicClient({transport:http('https://rpc.testnet.chain.robinhood.com')});
   if(await client.readContract({address:receipt.contract,abi,functionName:'recordedRound',args:[receipt.roundId]})){setNotice('This expedition is already recorded on the testnet.');return;}
   const data=encodeFunctionData({abi,functionName:'recordScore',args:[receipt.roundId,BigInt(receipt.day),BigInt(receipt.points),BigInt(receipt.deadline),receipt.signature]});
   const hash=await p.request({method:'eth_sendTransaction',params:[{from:accounts[0],to:receipt.contract,data,value:'0x0'}]});setTx({hash,status:'pending'});
   try{const result=await client.waitForTransactionReceipt({hash,timeout:90000});setTx({hash,status:result.status==='success'?'confirmed':'reverted'});}catch{setTx({hash,status:'pending'});setNotice('Confirmation is taking longer. Check your transaction in the explorer.');}
 });}
 const rankReady=config?.rankedReady;
 return <><header><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('home');}}><span className="brand-icon">✳</span><span>ATLAS<small>WORLD QUEST</small></span></a><nav aria-label="Main navigation">{[['home','Explore'],['leaderboard','Leaderboard'],['passport','My passport']].map(([id,label])=><button key={id} className={view===id?'nav-active':''} onClick={()=>navigate(id)}>{label}</button>)}</nav><div className="wallet-wrap">{player?<><button className="wallet" onClick={()=>setMenu(!menu)} aria-expanded={menu}>◉ {short(player.address)} ▾</button>{menu&&<div className="wallet-menu"><span>Signed in · no token approval</span><button onClick={()=>run(async()=>{await api('auth/logout',{});provider.current=null;setActiveProvider(null);setPlayer(null);setRound(null);setView('home');setMenu(false);})}>Disconnect</button></div>}</>:<button className="wallet" disabled={busy||!rankReady} onClick={connect}>{busy?'Connecting…':'Connect wallet'} <span>↗</span></button>}</div></header>
 <dialog className="wallet-dialog" ref={walletDialog} onCancel={()=>setWalletPicker(false)} onClose={()=>setWalletPicker(false)} aria-labelledby="wallet-title"><button className="dialog-close" aria-label="Close wallet selector" onClick={()=>setWalletPicker(false)}>Close</button><span className="eyebrow">YOUR EXPLORER PASSPORT</span><h2 id="wallet-title">Choose your wallet</h2><p>Connect, then sign a free message to save your progress. No gas or token approval.</p><div className="wallet-options">{wallets.map(w=><button key={w.id} className="outline" onClick={()=>signIn(w.provider)}>{w.name}<span>Connect</span></button>)}</div>{!wallets.length&&<div className="setup-note"><b>No wallet extension detected in this browser.</b><p>Open this game in Chrome, Brave or Edge with Rabby enabled, or paste the link into your mobile wallet browser. The browser inside Codex does not provide your wallet extension.</p><a href="https://rabby.io/" target="_blank" rel="noreferrer">Get Rabby from its official site</a></div>}<label className="wallet-url">Game link<input readOnly value="https://atlas-world-quest.vercel.app/" onFocus={e=>e.target.select()}/></label><p className="subtle">Already installed? Unlock your wallet, allow it on this site and refresh. Check the wallet extension for a pending request.</p><button className="text-button" onClick={()=>{setWalletPicker(false);startPractice();}}>Continue with free practice</button></dialog><main>{error&&<div className="message error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}>×</button></div>}{notice&&<div className="message" role="status">{notice}</div>}
 {view==='home'&&<><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> THE WORLD IS YOUR PLAYGROUND</div><h1>A little curiosity.<br/>A whole <em>new world.</em></h1><p>Chase clues across continents. Discover the assets behind everyday life. Make your next five answers an adventure.</p><div className="hero-actions"><button className="primary" disabled={busy||!rankReady} onClick={startRanked}>{player?'Start daily expedition':'Sign in to play ranked'} <span>↗</span></button><button className="text-button" disabled={busy} onClick={startPractice}>Try a practice round <span>→</span></button></div><div className="hero-notes"><span>✦ Free to play</span><span>◷ 5 questions</span><span>◎ Built for testnet</span></div>{config&&!rankReady&&<p className="setup-note">Practice is open. Ranked expeditions will open once the shared leaderboard is connected.</p>}</div><Globe/></section>
 <section className="expedition-strip"><div><span className="eyebrow">YOUR DAILY DEPARTURE</span><h2>Five stops. Countless discoveries.</h2></div><p>A fresh ranked expedition every UTC day.<br/>25 seconds per question. Up to 650 points.</p><span className="ticket">BOARDING PASS <b>001 / DAY</b></span></section>
 <section className="routes"><div className="section-heading"><div><span className="eyebrow">FOLLOW YOUR CURIOSITY</span><h2>Every clue opens a door.</h2></div><span className="subtle">Geography meets real-world assets</span></div><div className="route-grid"><article className="route-card"><div className="route-art city"><span>⌂</span><i>01</i></div><div><small>CITIES & LANDMARKS</small><h3>Where in the world?</h3><p>From a familiar skyline to a place you have yet to discover.</p></div></article><article className="route-card"><div className="route-art assets"><span>▥</span><i>02</i></div><div><small>THE REAL ECONOMY</small><h3>Connect the dots.</h3><p>Explore the ports, farms and infrastructure behind everyday life.</p></div></article><article className="route-card"><div className="route-art rwa"><span>◇</span><i>03</i></div><div><small>RWA CHECKPOINTS</small><h3>Know what you own.</h3><p>Learn why evidence matters more than a ticker or a token logo.</p></div></article></div></section>
 <section className="how"><div><span className="eyebrow">A PASSPORT WITH A PURPOSE</span><h2>Play. Learn. Leave your mark.</h2></div>{[['01','Connect your wallet','A free sign-in signature opens your player passport.'],['02','Take the daily expedition','Answer five questions. Earn points and regional stamps.'],['03','Record your journey','When enabled, save your verified result on Robinhood testnet.']].map(([n,h,p])=><article key={n}><b>{n}</b><h3>{h}</h3><p>{p}</p></article>)}</section>
 </>}
 {view==='play'&&current&&<section className="play"><div className="play-top"><button className="text-button" onClick={()=>navigate('home')}>← Explore</button><span className="pill">{practice?'PRACTICE · NO RANKED POINTS':'DAILY EXPEDITION · SERVER SCORED'}</span><span>{current.score} <small>PTS</small></span></div><div className="progress">{Array.from({length:5},(_,i)=><i key={i} className={i<(practice?practice.index+(practice.feedback?1:0):round.index)?'complete':''}/>)}</div>
 {current.question&&<div className="question-card"><div className="question-meta"><span>{current.question.region} / {current.question.category}</span><span className={remaining<=5?'timer low':'timer'} aria-label="Seconds remaining">◷ {remaining}s</span></div><div className="eyebrow">STOP {current.question.number} OF 5</div><h1>{current.question.prompt}</h1><div className="answers">{current.question.options.map((option,i)=><button key={i} disabled={busy||remaining===0} onClick={()=>answer(i)}><span>{String.fromCharCode(65+i)}</span>{option}<b>↗</b></button>)}</div>{remaining===0?<button className="primary" disabled={busy} onClick={()=>answer(-1)}>Time is up · reveal answer →</button>:<p className="subtle">Choose one answer. Correct answers earn 100 points + a streak bonus.</p>}</div>}
 {current.feedback&&<div className={`feedback ${current.feedback.correct?'correct':'incorrect'}`} role="status"><span className="feedback-icon">{current.feedback.correct?'✦':'◎'}</span><div className="eyebrow">{current.feedback.timedOut?'TIME TO DISCOVER':current.feedback.correct?'GREAT DISCOVERY':'SOMETHING NEW TO KNOW'}</div><h2>{current.feedback.correct?`+${current.feedback.points} points`:current.feedback.answer}</h2><p>{current.feedback.explanation}</p>{current.awaitingNext&&<button className="primary" onClick={next} disabled={busy}>Next destination →</button>}</div>}
 {current.done&&<div className="results"><span className="eyebrow">EXPEDITION COMPLETE</span><h1>{current.score}<em> points</em></h1><p>{current.correct} of 5 discoveries. {practice?'Practice points do not count toward rankings.':'Your ranked points are saved. Come back after 00:00 UTC for your next expedition.'}</p>{!practice&&<><div className="stamps">{current.stamps.map(s=><span key={s}>✦ {s}</span>)}</div><button className="primary" disabled={busy||!config?.onchainReady} onClick={record}>{busy?'Waiting for wallet / confirmation…':config?.onchainReady?'Record score on testnet ↗':'Onchain recording · coming soon'}</button><p className="subtle">Recording uses testnet ETH for gas. It does not mint ATLAS tokens or add more game points.</p>{tx&&<p role="status">Transaction {tx.status}. <a href={`${explorer}/tx/${tx.hash}`} target="_blank" rel="noreferrer">View on explorer ↗</a></p>}</>}<div className="hero-actions"><button className="text-button" onClick={()=>navigate('passport')}>Open my passport →</button><button className="text-button" onClick={startPractice} disabled={busy}>Play practice again →</button></div></div>}
 </section>}
 {view==='leaderboard'&&<section className="secondary"><div className="eyebrow">THE EXPLORERS CLUB</div><h1>Small discoveries.<br/><em>Big curiosity.</em></h1><p>Ranked expedition points. One attempt per wallet per UTC day. Equal scores are ordered by wallet address.</p><div className="tabs"><button className={period==='week'?'selected':''} onClick={()=>setPeriod('week')}>This week</button><button className={period==='all'?'selected':''} onClick={()=>setPeriod('all')}>All time</button></div><div className="leaderboard"><div className="board-row board-head"><span>RANK</span><span>EXPLORER</span><span>EXPEDITIONS</span><span>POINTS</span></div>{board===null?<p className="empty">{error?'Rankings could not be loaded. Try again later.':'Loading the explorers club…'}</p>:!board.length?<div className="empty"><b>Your adventure could start the story.</b><p>No completed ranked expeditions yet. No invented players or scores.</p><button className="primary" disabled={busy||!rankReady} onClick={startRanked}>Take the first expedition ↗</button></div>:board.map(p=><div className="board-row" key={p.address}><b>{String(p.rank).padStart(2,'0')}</b><a href={`${explorer}/address/${p.address}`} title={p.address} target="_blank" rel="noreferrer">{short(p.address)}{p.address===player?.address?' · YOU':''}</a><span>{p.completed}</span><strong>{p.points.toLocaleString()}</strong></div>)}</div><p className="subtle">Weekly rankings reset Monday at 00:00 UTC. These rankings are game scores, not official vibe/vibe reward eligibility.</p></section>}
 {view==='passport'&&<section className="secondary"><div className="eyebrow">YOUR EXPLORER IDENTITY</div><h1>A world of stories.<br/><em>One passport.</em></h1>{!player?<div className="empty"><p>Connect your wallet with a free sign-in signature to save ranked progress.</p><button className="primary" onClick={connect} disabled={busy||!rankReady}>Connect wallet ↗</button></div>:<><div className="passport"><div className="passport-top"><span className="brand-icon">✳</span><span>ATLAS WORLD QUEST<br/><small>EXPLORER PASSPORT · TESTNET</small></span><span className="passport-wallet">{short(player.address)}</span></div><div className="passport-stats"><div><b>{player.total.toLocaleString()}</b><span>ATLAS POINTS</span></div><div><b>{player.completed}</b><span>EXPEDITIONS</span></div><div><b>{player.stamps.length}/5</b><span>REGIONAL STAMPS</span></div></div><div className="stamp-grid">{regions.map((r,i)=><div key={r} className={player.stamps.includes(r)?'stamp earned':'stamp'}><span>{['☀','✧','⌁','⛰','≈'][i]}</span><b>{r}</b><small>{player.stamps.includes(r)?'DISCOVERED':'YET TO EXPLORE'}</small></div>)}</div></div><p className="subtle">Earn a regional stamp by answering a ranked question from that region correctly and completing the expedition.</p><button className="primary" disabled={busy} onClick={startRanked}>{player.today?'View today’s result':'Continue daily expedition'} →</button><h2>Recent expeditions</h2>{player.rounds.length?player.rounds.map(r=><div className="history" key={r.id}><span>{new Date(r.day*86400000).toLocaleDateString(undefined,{timeZone:'UTC'})}</span><span>{r.correct}/5 discoveries</span><b>{r.score} pts</b></div>):<p className="subtle">Your first completed expedition will appear here.</p>}</>}</section>}
 <section className="faucet"><div><span className="eyebrow">FUEL FOR YOUR TESTNET JOURNEY</span><h2>A little test ETH goes a long way.</h2><p>Get testnet funds from Robinhood’s official faucet. Practice and wallet sign-in need no gas.</p></div><a className="outline" href={faucet} target="_blank" rel="noreferrer">Open Robinhood faucet ↗</a></section>
 </main><footer><a className="brand" href="https://atlas-rwa.vercel.app/" target="_blank" rel="noreferrer"><span className="brand-icon">✳</span><span>AN ATLAS PRODUCT<small>BACK TO THE RESEARCH TERMINAL ↗</small></span></a><p>ATLAS Points track game progress. No cash value or guaranteed token conversion.<br/>Experimental testnet product. Not affiliated with Robinhood. No guaranteed builder rewards.</p><span>EXPLORE RESPONSIBLY.</span></footer></>;
}
createRoot(document.getElementById('root')).render(<App/>);
